### ISSUE TITLE
Dockerize the worker process

### ISSUE THREAD

**Issue by andygrove** [andygrove/datafusion-rs#19]
Create a Dockerfile to run the worker process (to try out the worker locally just run `cargo run worker`).

A/C

- There should be a bash script to create the worker binary (e.g. `cargo build --release`) and create the Docker image
- The Docker image should not contain Rust or Cargo, just the pre-compiled worker executable
- Port 80 should be exposed (for web UI and REST API)
- It should be possible to map a volume containing user-defined types and functions

**Comment by KenSuenobu** [comment]
Sure, this should be easy enough to do with the port mapping and volume stuff.  (Volume mapping will have to be done externally when `docker run` is specified, but this can be documented.)

Any specific directory structure you want me to use for the `Dockerfile` storage, or the build scripts?

**Comment by andygrove** [comment]
No, I didn't have anything specific in mind,

**Comment by KenSuenobu** [comment]
Pretty happy with the work: https://github.com/andygrove/datafusion-rs/pull/52
