### ISSUE TITLE
Move code to CircleCI for automated builds

### ISSUE THREAD

**Issue by KenSuenobu** [andygrove/datafusion-rs#20]
I can see that TravisCI is currently being used, but it might behoove us to move this project to CircleCI.

CircleCI 2.0 gives us a lot of flexibility, and allows us to run things in containers with versions of code that we desire.  It also means we don't have to maintain our own build cluster.

Just something to think about.  I can take this on if you want; shouldn't take longer than a few hours.

**Comment by andygrove** [comment]
I did some research before choosing travis and the main reason for choosing it is that it has first-class support for Rust, including parallel builds for different toolchains (stable, nightly, etc) on multiple operating systems and therefore has become the de-facto standard for Rust projects.

Seems to be working great so far so I don't think it's worth switching to be honest.
