### ISSUE TITLE
Google Cloud Dataflow

### ISSUE THREAD

**Issue by stephanbuys** [andygrove/datafusion-rs#45]
Hi all, any idea how this kind of project maps to something like Apache Beam?

**Comment by andygrove** [comment]
In the context of Apache Beam, DataFusion could potentially become an execution engine that Beam can deploy to.

**Comment by andygrove** [comment]
I suppose this could potentially help with interop with Spark.

**Comment by stephanbuys** [comment]
Awesome thanks
